### ISSUE TITLE
Dancer2::Plugin::Auth::Extensible::Provider::Unix has a lot of prerequisites

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2-Plugin-Auth-Extensible#19]
I am just trying to use Dancer2::Plugin::Auth::Extensible::Provider::Unix, and I have noticed it depends on quite a lot of modules. Specifically it uses Unix::Passwd::File  which depends on Event and AnyEvent.

I was  just wondering if there was a simpler solution for that.

**Comment by hvoers** [comment]
In my FreeBSD port the dependencies for extra Providers like Unix are optional.
If you don't use them, you don't have to install them.

Maybe all the providers should be external,
or only Example and Config can stay.

(Oh, that reminds me to include an option to depend on LDAP :) ).

**Comment by szabgab** [comment]
Yes, they are optional and that's good. I was just trying to experiment with the Unix provider and found it a bit demanding. I also released a unofficial version of https://metacpan.org/pod/Authen::PAM because of this..

**Comment by SysPete** [comment]
Commit 29066f9ae5e8049c18937f168619383b34bd3384 removes the dep on `Unix::Passwd::File` so closing this issue.
