### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by eserte** [PerlDancer/Dancer2-Plugin-Auth-Extensible#21]
http://matrix.cpantesters.org/?dist=Dancer2-Plugin-HTTP-Auth-Extensible%200.003 shows many test failures. Unfortunately analysis.cpantesters.org does not give a hint what's the problem here --- maybe it fails with newer Dancer2 versions, or it's caused by something else.

**Comment by SysPete** [comment]
Test failures are for Dancer2::Plugin::HTTP::Auth::Extensible which was forked from Dancer2::Plugin::Auth::Extensible to create a new plugin. I just checked cpantesters and issues have been resolved so I will not create a new issue against it and am closing this ticket.
