### ISSUE TITLE
Going directly to require_role page without logging in results in 500

### ISSUE THREAD

**Issue by druthb** [PerlDancer/Dancer2-Plugin-Auth-Extensible#28]
If a user types in the URL of a page controlled by require_role, but is not logged in yet, they get a 500 error:

Hook 'plugin.auth_extensible.login_required' does not exist at /usr/local/share/perl/5.14.2/Dancer2/Plugin/Auth/Extensible.pm line 317

What *should* happen, apparently, is that they should be redirected to the login, then on to their page, if they have the proper role.  I made a couple of halting attempts at this, but I think I don't understand the hook system quite thoroughly enough.  'Scuse my open-and-close pull request...that wasn't the right answer.

**Comment by racke** [comment]
Yes, in this case user should be redirected to the login.

**Comment by druthb** [comment]
Good to know I'm not losing my mind, then. Any idea why the hook call might be failing?

**Comment by SysPete** [comment]
Going through old issues and found this one. Seems we have been very lax - apologies.

We have a test case for this:

https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/blob/5027068c5a361feda9b7fd2d4bafd1c8ca1445a3/lib/Dancer2/Plugin/Auth/Extensible/Test.pm#L126-L139

We'd need more info to dig further if you still have this problem though I guess by this time you've given up.

**Comment by druthb** [comment]
Yes, I gave up on this a while back--we're handling that another way.  :/  Closing the issue.
