### ISSUE TITLE
LDAP is not part of the dist, remove the provider

### ISSUE THREAD

**Issue by hvoers** [PerlDancer/Dancer2-Plugin-Auth-Extensible#29]
It should be an external provider.
Please remove.

**Comment by SysPete** [comment]
I'd really like to move the LDAP provider into its own distro but at the moment it has no tests and thus I have no idea if it even works.

@hvoers if you have tuits for some tests they'd be much appreciated. :wink:

**Comment by hvoers** [comment]
The LDAP provider was added by Mark Meyer.

@ofosos Can you make a CPAN module for this?

**Comment by ofosos** [comment]
Yes, will do.
 
--
Mark Meyer
mark@ofosos.org
 
 
On Fri, Jun 17, 2016, at 05:39 AM, Henk van Oers wrote:
> The LDAP provider was added by Mark Meyer.
> @ofosos[1] Can you make a CPAN module for this?
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>

Links:

  1. https://github.com/ofosos
  2. https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/issues/29#issuecomment-226673188
  3. https://github.com/notifications/unsubscribe/AA2R7-PBE-9l56nE3KDTqjTPkqNEKZA1ks5qMhbngaJpZM4EOn_j

**Comment by SysPete** [comment]
I have a working LDAP provider in one of my branches. I've changed quite a bit from @ofosos 's original provider which will hopefully make it useful for a wider variety of LDAP backends. Will create a new repo soon and link here.

**Comment by SysPete** [comment]
LDAP provider has now been removed from this repository and can be found here: https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible-Provider-LDAP

If there is anything you would like to see added/improved please create an issue against this new repo. New version of LDAP provider has been released to CPAN.
