### ISSUE TITLE
bin/generate-crypted-password belongs to D1 version

### ISSUE THREAD

**Issue by hvoers** [PerlDancer/Dancer2-Plugin-Auth-Extensible#30]
Please rename or remove bin/generate-crypted-password
Do not install in the same place.

**Comment by hvoers** [comment]
Do I need to make a PR?

**Comment by racke** [comment]
I guess we could rename it to avoid conflict with Dancer1 and probably other scripts,
maybe dancer2-generate-crypted-password. What do you think?

**Comment by hvoers** [comment]
Rename is fine. And then please make a new CPAN version so I can make the FreeBSD ports updates.

**Comment by racke** [comment]
OK, sure.

**Comment by hvoers** [comment]
Do not forget merging https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/pull/23

**Comment by hvoers** [comment]
Any news?

**Comment by hvoers** [comment]
You forgot this problem in your release :(

**Comment by racke** [comment]
Too much already in the new release already 8-). I'll put this in the next few days.
