### ISSUE TITLE
Stricter matching for for default routes?

### ISSUE THREAD

**Issue by evanernest** [PerlDancer/Dancer2-Plugin-Auth-Extensible#31]
Perhaps there are applications I'm not thinking of, but the matching for the default routes included with the plugin seems too open. I noticed that if the default is used for the login page ('/login'), requests for both '/login' and '/foo/login' will be handled by the plugin's login_page_handler. This seems like a bug to me, but maybe I'm not thinking it through. Happy to do the PR, if I'm right.

Thoughts?

**Comment by abeverley** [comment]
Agreed. I'm sure if you do a PR then Racke will be happy to merge in due course.

**Comment by racke** [comment]
On 08/09/2015 06:14 PM, Andy Beverley wrote:
> Agreed. I'm sure if you do a PR then Racke will be happy to merge in due course.
> 

Indeed :-)

Regards
          Racke


-- 
Perl and Dancer Development

Visit our Perl::Dancer conference 2015.
More information on https://www.perl.dance.

**Comment by evanernest** [comment]
Done:

https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/pull/32

Thanks all!

**Comment by racke** [comment]
Closed by PR #32
