### ISSUE TITLE
support for array of realms, or ability to determine realm process order ?

### ISSUE THREAD

**Issue by aka-raj** [PerlDancer/Dancer2-Plugin-Auth-Extensible#37]
Currently DPAE::authenticate_user when handling 'require_role' from route file uses a hash to store realms:   keys %{ $settings->{realms} }

this means it is not possible to have a user in more than 1 realm and determine which one 'wins'. Example might be I want a role that doesn't exist in my database realm so would be useful to put a config realm 1st with just limited data and expect that to match 1st without going to next realm. At the moment realm database gets processed before realm config.

One way might be to pass the realm along with require_role 'Foo', or is it too late by then, the roles are already allocated from a realm?

**Comment by abeverley** [comment]
Clarification: when authenticating, user realms should be checked in the order that they are specified in the config file.

**Comment by SysPete** [comment]
We cannot control priority based on order in a config file so I suggest a new `realm_priority` setting or something along those lines. Would this be acceptable?

**Comment by SysPete** [comment]
@aka-raj and @abeverley I've created a PR which implements this via a 'priority' config option added to the realm configuration: https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/pull/52

Please have a look at the PR if you have time.

**Comment by SysPete** [comment]
I've merged the PR via commit 5027068c5a361feda9b7fd2d4bafd1c8ca1445a3.
