### ISSUE TITLE
documented 'disable_roles' doesn't exist in DPAE codebase

### ISSUE THREAD

**Issue by aka-raj** [PerlDancer/Dancer2-Plugin-Auth-Extensible#38]
Sample configuration in DPAE and Provider::Database - disable_roles: 0/1. Doesn't seem to exist in plugin codebase.

**Comment by abeverley** [comment]
No, but I've just started using it in Provider::DBIC, so it is still a valid config option.

One thing that could be improved, however, is the passing of the option to the providers. I had to use a rather hacky ```$dsl->config->{plugins}->{'Auth::Extensible'}->{disable_roles}```, so I'll leave this issue open to flag a fix for that at some point.

**Comment by SysPete** [comment]
I've been playing with this and am wondering how best to handle routes with `require_role` or similar when `disable_roles` is true. My feeling right now is that we should return `500 Internal Server Error`. Other ideas?

ping @aka-raj @abeverley @racke

**Comment by racke** [comment]
Shouldn't we barf at plugin load time about this conflict?

**Comment by SysPete** [comment]
@racke that is an option for the route decorators but the other keywords can only throw runtime errors.

**Comment by SysPete** [comment]
PR #58 throws at runtime for all uses of role keywords including decorators. I'm inclined to agree with @racke regarding throwing at load time for route decorators. Waiting for more comments before I go any further.

**Comment by SysPete** [comment]
Closed by commit 4d4c36e674d56a3bdd7a0759f5434654807aabe0
