### ISSUE TITLE
Commit 153200d of file Extensible.pm is not available on CPAN

### ISSUE THREAD

**Issue by jobec** [PerlDancer/Dancer2-Plugin-Auth-Extensible#39]
The changes in Extensible.pm that were done in commit 153200d are not available on CPAN.

Because of this there's a redirect loop between a route needing a certain role and the /login/denied page if the user hasn't been assigned that role.

If I manually edit Extensible.pm to include the regex changes, things start working like they should.

Tested on Dancer2 version  0.163000 and Perl 5.20.3

**Comment by racke** [comment]
That's correct. I'm going to prepare a new release. Thanks for the notice, @jobec!

**Comment by racke** [comment]
Dancer2::Plugin::Auth::Extensible 0.402 was just released.
