### ISSUE TITLE
undefined subroutine database

### ISSUE THREAD

**Issue by jacqueslareau** [PerlDancer/Dancer2-Plugin-Auth-Extensible#4]
I recently get this error:

Route exception: Undefined subroutine &Dancer2::Plugin::Auth::Extensible::Provider::Database::database called at /usr/local/share/perl5   /Dancer2/Plugin/Auth/Extensible/Provider/Database.pm line 208.

Just upgraded to Dancer2 0.156000 and D::P::Database to 2.12.

**Comment by VinceW** [comment]
FYI 
I'm having the same notices as @jacqueslareau is describing.
Using Dancer2: 0.158000 and D::P::Database 2.12

**Comment by abeverley** [comment]
I don't know the exact details, but the full DSL is not passed to plugins on each call any more. For the DBIC plugin, I worked around this by capturing the requried DSL references on plugin load.

**Comment by neiromancer** [comment]
Same error 
"Cannot load provider Dancer2::Plugin::Auth::Extensible::Provider::Database: Can't locate object method "dsl" via package "Dancer2::Plugin::Auth::Extensible::Provider::Database" at /usr/local/share/perl/5.18.2/Dancer2/Plugin.pm line 85."

Dancer2 0.159002
Dancer2::Plugin::Database 2.12
Dancer2::Plugin::Auth::Extensible 0.304

**Comment by hvoers** [comment]
See also PR #13

**Comment by hvoers** [comment]
After PR #13 the following lines in "Dancer2::Plugin::Auth::Extensible::Provider::Database"

my $database = database($settings->{db_connection_name})

can be changed into:

my $database = realm_dsl->database($settings->{db_connection_name})

**Comment by racke** [comment]
OK, please test if this fixes the problem.

**Comment by hvoers** [comment]
You forgot the other line.
(grep db_connection_name Extensible/Provider/Database.pm)

**Comment by racke** [comment]
Sorry, please try again.

**Comment by hvoers** [comment]
I have tested PR #13 with ...Provider::Usergroup (using D2::P::Passphrase and D2::P::DBIC)
That works.
With ...Provider::Database I have less luck.
It runs in an error in Dancer2::Plugin::Database
I will make some more test-apps e.g. just using D2::P::Database and send other PRs.

**Comment by racke** [comment]
I noticed that too. So is there any difference in the DBIC and Database providers in this regard?

**Comment by hvoers** [comment]
Yes, there are differences in the DBIC and Database providers.
See also https://github.com/PerlDancer/Dancer2/pull/865

**Comment by av8r** [comment]
any update ?

**Comment by arjancwidlak** [comment]
Any update or is there perhaps a working version on github already?

**Comment by abeverley** [comment]
I suspect the answer lies in the rework of the Dancer2 plugin architecture: http://lists.preshweb.co.uk/pipermail/dancer-users/2015-April/004512.html

Not sure what the status of this is though.

**Comment by abeverley** [comment]
@arjancwidlak - can you use the DBIC provider instead?

**Comment by arjancwidlak** [comment]
Yes, I suppose I can. Just had a look. And what a nice idea DBICx::Sugar is. 
I looked at D2::P::A::E::P::Database more as a quick stand-in before I found out it was broken.

**Comment by igoratencompass** [comment]
Is this still broken? I'm getting the same error on 0.162000

**Comment by abeverley** [comment]
I suspect it won't be fixed until ```Dancer2::Plugin2``` is released, which fixes some fundamental issues with the plugin system that make features like this difficult.

**Comment by SysPete** [comment]
Testing D2PAE v0.501 with Database provider using Dancer2::Plugin::Database v2.13 I see no issues with any of the following Dancer2 versions:

0.150000, 0.156000, 0.158000, 0.159002, v0.160000, v0.162000, 0.166000, 0.166001

This covers all Dancer2 versions mentioned in this issue so I am closing this ticket. If anyone is still having this issue please upgrade Dancer2::Plugin::Database to v2.13 before reopening this issue.

Many thanks.
