### ISSUE TITLE
Non-base tests are not being executed

### ISSUE THREAD

**Issue by abeverley** [PerlDancer/Dancer2-Plugin-Auth-Extensible#42]
When I run some none-base tests, with something like

```Dancer2::Plugin::Auth::Extensible::Test::testme($app, 'create_user');```

the create_user test is not run. Is this a bug, or am I calling it incorrectly? The following fixes it for me, but I'm not sure whether I'm doing something wrong:
```
- eval "_test_$name()";
+ my $test = eval "_test_$name()";
+ test_psgi $app, $test;
```

**Comment by SysPete** [comment]
Good catch! As you can see I hadn't actually started using that part so bugs expected. I think I prefer something more like:
```
my $test = "_test_$name";
test_psgi $app, $test();
```
assuming it works. Not sure why I was thinking about eval and would prefer not to use it if possible.

**Comment by abeverley** [comment]
I can't get that to work I'm afraid. The code above results in a syntax error. I've tried various combinations of ```$test->()```, ```no strict 'refs'``` and ```my $test = sub {...}```. Any ideas?
