### ISSUE TITLE
Function "get_user_details" is not defined, when I make call it

### ISSUE THREAD

**Issue by mongoostic** [PerlDancer/Dancer2-Plugin-Auth-Extensible#44]
version of module .402.

**Comment by SysPete** [comment]
Hi @mongoostic any chance you could retest against latest release 0.501? If you are using the DBIC provider please also upgrade that to latest version. Please also let us know which provider you are using if you still have issues.

**Comment by SysPete** [comment]
@mongoostic have you had chance to test against a newer version?

**Comment by mongoostic** [comment]
Hello, Peter!

Unfortunately, no, sorry.

with best regards, Anton

17.06.2016, 00:35, "Peter Mottram" <notifications@github.com>:

**Comment by SysPete** [comment]
Plugin2 reworked version definitely has this keyword and we have tests that verify this so I'm closing this issue. Feel free to reopen if you have more info. TIA
