### ISSUE TITLE
Plugin password_reset tests failure

### ISSUE THREAD

**Issue by racke** [PerlDancer/Dancer2-Plugin-Auth-Extensible#66]
http://www.cpantesters.org/cpan/report/7e7f6abc-b0e2-11e6-ba10-8837101c79ff

**Comment by SysPete** [comment]
Those tests have all been rewritten following the move to Dancer2::Plugin::Email so this failure will never reappear (or at least not in the same form) after the next release. Let's leave this open for now anyway as a reminder.

**Comment by SysPete** [comment]
This should be fixed by 52f2e4b1bd2127e1f228022f69aa8e089784d616 we just have to wait and see what the smokers come up with.

**Comment by SysPete** [comment]
Closing as there have been no related test failure reports for a very long time.
