### ISSUE TITLE
Check for HTTP::BrowserDetect in tests

### ISSUE THREAD

**Issue by abeverley** [PerlDancer/Dancer2-Plugin-Auth-Extensible#67]
It would be useful if tests could begin by checking that ```HTTP::BrowserDetect``` is installed. I realise it's listed as a dependency, but if it's missing for some reason then tests fail with mysterious errors such as:

```t/login-without-redirect.t ........... 1/? 
#   Failed test 'Trying a require_login page with *no* User-Agent header gets 401'
#   at t/login-without-redirect.t line 65.
#          got: '500'
#     expected: '401'
```

**Comment by SysPete** [comment]
Closed by e6f1c6eff4a2f69733c48c7800dd71c68f7921b0
