### ISSUE TITLE
Add a before_logout hook

### ISSUE THREAD

**Issue by sonntagd** [PerlDancer/Dancer2-Plugin-Auth-Extensible#69]
Sometimes it would be good to do some cleanup on user logout. I suggest to add a hook called `before_logout` that still has the session information available to tidy up.

**Comment by SysPete** [comment]
@sonntagd sounds good to me.

**Comment by sonntagd** [comment]
I created the pull request #70 that works great for me. Please review.

**Comment by abeverley** [comment]
PR has been merged so closing this issue.
