### ISSUE TITLE
return_url not correct

### ISSUE THREAD

**Issue by mark-00** [PerlDancer/Dancer2-Plugin-Auth-Extensible#74]
There are 2 problems with the return_url parameter used in the login handeler

I start my app as:  plackup -r -R lib --port 3000 --server Starman --signal-on-term=QUIT --workers 5 bin/app.psgi
The resouce url  is http://dancerapp1:3000/sake
The loginpage url is http://dancerapp1:3000/login?return_url=%2Fsake
It returns to http://dancerapp1:3000//sake
Notice the double /. It works but slashes keeps stacking up.

A second problem is when using the plackup parameter --path
I start my app as:  plackup -r -R lib --port 3000 --server Starman --signal-on-term=QUIT **--path=/dancerapp1** --workers 5 bin/app.psgi
The resource url is http://dancerapp1:3000/dancerapp1/sake
The login url is http://dancerapp1:3000/dancerapp1/login?return_url=%2Fdancerapp1%2Fsake
It returns to http://dancerapp1:3000/dancerapp1//dancerapp1/sake
Notice the extra dancerapp1

The suggested fix is to replace the following line at the end of the subroutine  _check_for_login in the file Dancer2/Plugin/Auth/Extensible.pm
from :            $plugin->login_page, { return_url => $request->request_uri }
to :                $plugin->login_page, { return_url => **substr($request->path,1)** }

**Comment by niceperl** [comment]
I'm experimenting the same problem on 0.704 revision

**Comment by abeverley** [comment]
The "second problem" described above has been fixed in c01719f
