### ISSUE TITLE
Login redirect fails when app mounted on subdirectory

### ISSUE THREAD

**Issue by ehuelsmann** [PerlDancer/Dancer2-Plugin-Auth-Extensible#82]
In our code base, I'm working to implement a number of Dancer apps which each have their own subpath within a shared URL space (for now):

```perl
builder {
     mount '/app1', $psgi_app;
     mount '/setup', $dancer2_app;
}
```

When navigating to `http://example.org/setup` (unauthenticated), Auth-Extensible redirects that to `http://example.org/setup/login?return_url=%2Fsetup%2F`. After succesfully logging in, the user is routed to `http://example.org/setup/setup`.

Note the double `setup` there. I'm thinking that either the return URL is wrong (should be `/`) or the redirect redirecting to `/setup/` is wrong (should *not* take the prefix into account).

**Comment by abeverley** [comment]
Fixed in c01719f
