### ISSUE TITLE
Option no_default_pages does not work as aspected

### ISSUE THREAD

**Issue by hvoers** [PerlDancer/Dancer2-Plugin-Auth-Extensible#9]
It also removes the handlers.
Option no_login_handler is in the pod, but not in the code.

**Comment by racke** [comment]
OK, I'll check this out. Probably lost during the migration from Dancer1.

**Comment by abeverley** [comment]
Should be fixed in the above PR. @hvoers would you mind testing please?

**Comment by hvoers** [comment]
Yes, I will test this later this week.

**Comment by hvoers** [comment]
I am sorry, it does not work for me.
Using Dancer2-Plugin-Auth-Extensible-0.305
and  Dancer2-0.159002 and a route:

get '/login' => sub {
    template 'my_login';
};

Config: no_default_pages: 1

... shows the default page :(

**Comment by abeverley** [comment]
Could you check that the module file you're using has this code in please?

https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/blob/master/lib/Dancer2/Plugin/Auth/Extensible.pm#L603

I've just tried it myself and it works okay for me.

**Comment by hvoers** [comment]
Solved!
In my config I had "no_default_pages: 1" under a realm.
It should go direct under

plugins:
  Auth::Extensible:
    no_default_pages: 1

/me bad. Sorry.
Works fine now.

**Comment by racke** [comment]
OK, ready to close this now.
