### ISSUE TITLE
logged_in_user when not logged in: return undef?

### ISSUE THREAD

**Issue by cxw42** [PerlDancer/Dancer2-Plugin-Auth-Extensible#92]
Situation: passing `logged_in_user` to a template when no user is logged in.

Symption: "odd number of elements in hash" warnings in the `template` call.

The warnings appear to originate from here in `logged_in_user`:

https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/blob/55a374aeabf526c3baa37bb2a1c6ab508bb0952d/lib/Dancer2/Plugin/Auth/Extensible.pm#L609

If no user is logged in, and `logged_in_user` is called in list context, the bare `return` returns an empty list.  That means that I can't say:

    template 'foo' => {
        user => logged_in_user
    };

instead, I have to say 

    template 'foo' => {
        user => scalar logged_in_user
    };

It's the same behaviour as this:

    $ perl -Mstrict -Mwarnings -E 'sub foo { return } ; my $h = { key => foo }'
    Odd number of elements in anonymous hash at -e line 1.
    $ perl -Mstrict -Mwarnings -E 'sub foo { return undef } ; my $h = { key => foo }'
        # Runs with no warnings

Would it be reasonable for `logged_in_user` to return an explicit `undef` or other falsy value even in list context when no user is logged in?  Thanks for considering this question!  Please let me know if this report is not sufficiently clear.

**Comment by abeverley** [comment]
Thanks for this, I think ```logged_in_user``` explicitly returning ```undef``` makes a lot of sense. Fixed in d4f74c1
