### ISSUE TITLE
Fails with recent Dancer2 releases

### ISSUE THREAD

**Issue by andk** [PerlDancer/Dancer2-Plugin-Auth-Extensible#93]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/ff48fce4-790c-11ea-85c5-ce21298dc52a

**Comment by GeekRuthie** [comment]
I'm seeing the same problem, installing this plugin against Dancer2 0.300001

**Comment by cromedome** [comment]
This is 99.9% likely due to the change introduced in https://github.com/PerlDancer/Dancer2/pull/1461. The tests in D2::P::A::E should be changed to the shorter URL to match the change made in Dancer2. I didn't think to check this when I packaged the last D2 release, sorry. PRs welcome :)

**Comment by GeekRuthie** [comment]
PR on the way---should have something shortly.

**Comment by GeekRuthie** [comment]
I've created [a PR](https://github.com/PerlDancer/Dancer2-Plugin-Auth-Extensible/pull/94) that addresses this issue.

**Comment by SysPete** [comment]
Closed by #94. Thank you @GeekRuthie!
